import Head from "next/head";
import Navbar from "./components/navbar/navbar";
import Container from "@mui/material/Container";
import { pages, links, secondLinks } from "./pages";
import Subscribe from "./components/subscribe/subscribe";
import Body from "./components/body/body";
import Footer from "./components/footer/footer";

import { db } from "./firebase/firebase";
import {
  collection,
  query,
  getDocs,
  orderBy,
  Timestamp,
} from "firebase/firestore";
export function convert(seconds, nano) {
  return new Timestamp(seconds, nano).toDate().toDateString();
}
const fetch = async () => {
  const data = [];
  const q = query(collection(db, "blogs"), orderBy("date", "desc"));
  const querySnapshot = await getDocs(q);
  querySnapshot.forEach((doc) => {
    data.push({
      ...doc.data(),
      id: doc.id,
      date: convert(doc.data().date.seconds, doc.data().date.nanoseconds),
      comments: [],
    });
  });
  return data;
};

export async function getStaticProps() {
  const data = await fetch();
  return {
    props: { data: data },
  };
}
export default function Home({ data }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Container
        disableGutters
        maxWidth="xl"
        sx={{ overflowY: "scroll", height: "100vh" }}
      >
        <Navbar navItems={pages} icons name="YorBest" links={links} />
        <Body data={data} />
        <Subscribe />
        <Footer />
        {/* <div class="sharethis-privacy-policy"></div> */}
      </Container>
    </>
  );
}
